__include__: [
  '../../dataset/coco_detection.yml',
  '../../runtime.yml',
  '../include/dataloader.yml',
  '../include/optimizer.yml',
  '../include/rtdetrv2_r50vd.yml',
]


output_dir: ../output/rtdenatrx

RTDETR: 
  backbone: EfficientViT
  encoder: HybridNA1DEncoder


EfficientViT:
  name: l1
  freeze_at: 0
  return_idx: [2, 3, 4]
  freeze_norm: True
  pretrained: True 


HybridNA1DEncoder:
  in_channels: [128, 256, 512]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  
  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'

  kernel_size: 63


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  num_layers: 5


optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001