__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


# output_dir: ./output/rtdetrv2_r101vd_6x_coco
output_dir: ../output/test


PResNet:
  depth: 101


HybridEncoder:
  # intra
  hidden_dim: 256
  dim_feedforward: 1024


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]


optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000004
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001
